Repository Damagucci-Juice/sidedish, pull requests merged in 2022-04, with the labels that each got.

#13 [UI] Collection View Section Inset 과 Collection View 를 Table View 처럼 표현
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Base/AppDelegate.swift
  SideDish/SideDish/Base/Base.lproj/Main.storyboard
  SideDish/SideDish/Base/Info.plist
  SideDish/SideDish/Base/SceneDelegate.swift
  SideDish/SideDish/Support/Font.swift
  SideDish/SideDish/View/DishCell.xib
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/View/PaddingLabel.swift
  SideDish/SideDish/View/SectionHeader.swift
Labels: bug, help wanted, implement

#16 [UI] DishCell 일부 수정
  SideDish/SideDish/View/DishCell.swift
  SideDish/SideDish/View/DishCell.xib
Labels: implement, refactoring

#18 주말까지 구현사항
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/View/SectionHeader.swift
Labels: enhancement, implement

#22 [모델링]서버로 부터 패치 해와서 Cell에 데이터 입력 성공 but...순서 뒤죽박죽
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Model/DiscountType.swift
  SideDish/SideDish/Model/DishCellRepository.swift
  SideDish/SideDish/Model/DishDetailRepository.swift
  SideDish/SideDish/Model/Entity/DetailData.swift
  SideDish/SideDish/Model/Entity/DishCellInfo.swift
  SideDish/SideDish/Model/Entity/DishDetail.swift
  SideDish/SideDish/Model/Product.swift
  SideDish/SideDish/Support/CellFactory.swift
  SideDish/SideDish/Support/NetworkError.swift
  SideDish/SideDish/Support/ProductSort.swift
  SideDish/SideDish/View/DishCell.swift
  SideDish/SideDish/View/DishCell.xib
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/ViewModel/DishCellViewModel.swift
Labels: enhancement, help wanted, implement

#20 [UI] DetailView에 있는 amountStepper에 action 추가하기
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Extensions/String+.swift
  SideDish/SideDish/View/DetailView.swift
Labels: implement

#25 [모델링] Home View Controller수정 요청 사항 반영
  SideDish/.SwiftLint.yml
  SideDish/SideDish/Base/Base.lproj/Main.storyboard
  SideDish/SideDish/Base/Info.plist
  SideDish/SideDish/Support/CellFactory.swift
  SideDish/SideDish/View/HomeViewController.swift
Labels: bug
